[DataFrame의 index 다루기]

[1] 모듈 로딩 및 데이터 준비 <hr>

In [153]:
# [1-1] module 로딩
import pandas as pd


[DataFrame - reindex] <hr>

In [154]:
# [1-2] 데이터 준비비
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9],  'c3':[10,11,12], 'c4':[13,14,15]}
DF=pd.DataFrame(dict_data,index=['r0','r1','r2'])


In [155]:
# [2-2] 데이터 속성 확인
from utils import *
print_attribute(DF,'DF')

------[DF]-------
dtype: c0    int64
c1    int64
c2    int64
c3    int64
c4    int64
dtype: object
col: Index(['c0', 'c1', 'c2', 'c3', 'c4'], dtype='object')
idx: Index(['r0', 'r1', 'r2'], dtype='object')
dim: 2
shape: (3, 5)
values: 
[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]


[3] 인덱스 재설정 <hr>

In [156]:
# [3-1] index변경
new_index=['r0','r1','r2','r3','r4']
DF.reindex(new_index)

c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [157]:
new_index=['one','two','three','r3','r4']
DF.reindex(new_index)

c0  c1  c2  c3  c4
one   NaN NaN NaN NaN NaN
two   NaN NaN NaN NaN NaN
three NaN NaN NaN NaN NaN
r3    NaN NaN NaN NaN NaN
r4    NaN NaN NaN NaN NaN

In [158]:
DF1=DF.reindex(new_index,axis=1,fill_value=0)
DF.reindex(columns=new_index,fill_value=5)

one  two  three  r3  r4
r0    5    5      5   5   5
r1    5    5      5   5   5
r2    5    5      5   5   5

In [159]:
DF1.iloc[0:3]=[20,10,30,40,10]
print(DF1)
DF1.reindex(['r0','r3','r1'],fill_value=0)

    one  two  three  r3  r4
r0   20   10     30  40  10
r1   20   10     30  40  10
r2   20   10     30  40  10


one  two  three  r3  r4
r0   20   10     30  40  10
r3    0    0      0   0   0
r1   20   10     30  40  10

In [160]:
# [3-3] col -> 'c0','c1','c2','c5
cols=['c0','c1','c2','c5']
DF1=DF.reindex(cols,axis=1)      

In [161]:
# [3-4] col -> 'c0','c1','c2','c5
index=['one','first','two','second']
DF1=DF.reindex(index,fill_value=0)  
DF1.iloc[[0,2]]=[1,4,7,10,13]
print(DF1)    

        c0  c1  c2  c3  c4
one      1   4   7  10  13
first    0   0   0   0   0
two      1   4   7  10  13
second   0   0   0   0   0


- 연속된 데이터의 인덱스의 reindex <hr>


In [165]:
data_index=pd.date_range('1/20/2025',periods=6,freq='D')
data_index
# numpy 불러오기
import numpy as np
dict_data = {'c0':[0,1,2,np.nan,5,6]}
DF2=pd.DataFrame(dict_data, index=data_index)
print(DF2)
# ------------------------------------------------------
data_index=pd.date_range('1/20/2025',periods=10,freq='D')
DF2.reindex(data_index,method='ffill')


             c0
2025-01-20  0.0
2025-01-21  1.0
2025-01-22  2.0
2025-01-23  NaN
2025-01-24  5.0
2025-01-25  6.0


c0
2025-01-20  0.0
2025-01-21  1.0
2025-01-22  2.0
2025-01-23  NaN
2025-01-24  5.0
2025-01-25  6.0
2025-01-26  6.0
2025-01-27  6.0
2025-01-28  6.0
2025-01-29  6.0